logging:
  level:
     org.springframework.security: DEBUG

github:
   client:
      clientId: *id клиента*
      clientSecret: *секретный ключ клиента*
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
   resource:
      userInfoUri: https://api.github.com/user